### ISSUE TITLE
finish up v2.7 checklist

### ISSUE THREAD

**Issue by Fluffyalien1422** [Fluffyalien1422/asn#25]
- [x] #23
- [x] add tutorial book entry for portable storage network
- [x] #26
- [x] #27
- [x] add wireless transmitter tutorial book entry
- [x] add recipes for storage power bank & portable storage network & wireless transmitter
- [x] make portable storage network drop with it's energy stored
